name: stepback
description: "Local History Augmented Reality (AR) Explorer"

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.5
  flutter_localizations:
    sdk: flutter
  get_it: ^7.6.7
  responsive_framework: ^1.4.0
  http: ^1.2.1
  retrofit: ^4.0.1
  json_annotation: ^4.9.0
  # In a directory below this file 
  # flutter_plugin_forks\ar_flutter_plugin
  ar_flutter_plugin: 
    path: ../flutter_plugin_forks/ar_flutter_plugin
  google_maps_flutter: ^2.6.1
  hive: ^2.2.3
  firebase_core: ^2.31.0
  cloud_firestore: ^4.17.3
  firebase_storage: ^11.7.5
  url_launcher: ^6.3.0
  permission_handler: ^10.4.5
  connectivity_plus: ^6.0.5
  firebase_auth: ^4.20.0
  location: ^6.0.2
  geocoding: ^3.0.0
  dio: ^5.0.3
  flutter_compass:
    git:
      url: https://github.com/Dapucla/flutter_compass.git
  image_picker: ^1.1.2
  cached_network_image: ^3.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  retrofit_generator: ^9.1.2
  build_runner: ^2.4.6
  json_serializable: ^6.6.1
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
    - assets/models/
